fastapi:
  debug: true

api:
  versions:
    current: v1
    supported:
    deprecated:
    unsupported:

databases:
  default:
    ENGINE: 'mongodb'
    DRIVER: 'motor'
    NAME: 'todo-db'
    USER: 'todo-user'
    PASSWORD: 'ToDo2020'
    HOST: 'mongo' 
    PORT: 27017